### ISSUE TITLE
Scroll on X axis needs to be removed 

### ISSUE THREAD

**Issue by nitin-pandita** [nitin-pandita/Notes-Collector#1]
![scroll](https://user-images.githubusercontent.com/91310284/236368937-12eba75d-d9d9-4642-9ed2-53d770bf514c.png)

**Comment by arthurkyambadde** [comment]
Hello there. Can I help with this?

**Comment by nitin-pandita** [comment]
> Hello there. Can I help with this?

sure @arthurkyambadde go for it
